Livy fix
IBM/hdp-search-spark-recommender pull request #20
Opened 2018-07-09 00:59 UTC by stevemart

2018-07-09 11:12 UTC, stevemart commented
@rhagarty this lgtm, please review.

2018-07-09 15:07 UTC, rhagarty requested changes
@dilipbiswal I can't view the notebook in github which usually indicates some json issue.

2018-07-09 15:12 UTC, stevemart commented
@rhagarty seems to render fine on nbviewer: http://nbviewer.jupyter.org/github/IBM/hdp-search-spark-recommender/blob/22236a4333d4f90a41456e2ab198f9762fdc7dd6/notebooks/solr-hdp-spark-recommender.ipynb ... maybe something is up with the github service? 🤷‍♂️

2018-07-09 15:12 UTC, rhagarty commented on README.md
> -hadoop fs -put
@dilipbiswal - can you provide context about where this command is issued?

2018-07-10 14:09 UTC, rhagarty approved these changes

2018-07-10 14:09 UTC, rhagarty commented
changes to README coming

2018-07-10 14:09 UTC, merged